server:
  port: 8002
  shutdown: graceful

application:
  title: matching-king

spring:
  application:
    name: matching-api-service
  jackson:
    default-property-inclusion: non_null

logging:
  file:
    path: ${file-path.root}/logs
    name: ${spring.config.activate.on-profile}
  config: classpath:logback-${spring.config.activate.on-profile}.xml

decorator:
  datasource:
    p6spy:
      enable-logging: false

---
# LOCAL
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/random_matching?serverTimezone=UTC&characterEncoding=UTF-8
    username: random_matching
    password: random_matching!@34
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100

decorator:
  datasource:
    p6spy:
      enable-logging: true

file-path:
  root: /Users/ds/Downloads/springboot/${application.title}/${spring.application.name}

---
# TEST
spring:
  config:
    activate:
      on-profile: test
  datasource:
    master:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:13306/random_matching?serverTimezone=UTC&characterEncoding=UTF-8
      username: random_matching
      password: random_matching!@34
    slaves:
      - name: slave-1
        url: jdbc:mariadb://localhost:13307/random_matching?serverTimezone=UTC&characterEncoding=UTF-8
      - name: slave-2
        url: jdbc:mariadb://localhost:13308/random_matching?serverTimezone=UTC&characterEncoding=UTF-8
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100

decorator:
  datasource:
    p6spy:
      enable-logging: false
    ignore-routing-data-sources: true
    enabled: false

file-path:
  root: /Users/ds/Downloads/springboot/${application.title}/${spring.application.name}

---
# POSTGRESQL
spring:
  config:
    activate:
      on-profile: postgresql-test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/random_matching
    username: random_matching
    password: random_matching!@34
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100

decorator:
  datasource:
    p6spy:
      enable-logging: true

file-path:
  root: /Users/ds/Downloads/springboot/${application.title}/${spring.application.name}