server:
  port: 8002
  shutdown: graceful

application:
  title: matching-king
  
spring:
  application:
    name: matching-api-service
  jackson:
    default-property-inclusion: non_null

logging:
  file:
    path: ${file-path.root}/logs
    name: ${spring.config.activate.on-profile}
  config: classpath:logback-${spring.config.activate.on-profile}.xml

decorator:
  datasource:
    p6spy:
      enable-logging: false

---
# LOCAL
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/random_matching?serverTimezone=UTC&characterEncoding=UTF-8
    username: random_matching
    password: random_matching!@34
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      #      ddl-auto: update
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

file-path:
  root: /Users/ds/Downloads/springboot/${application.title}/${spring.application.name}

decorator:
  datasource:
    p6spy:
      enable-logging: true

---
# TEST
spring:
  config:
    activate:
      on-profile: test
  datasource:
    master:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:13306/random_matching?serverTimezone=UTC&characterEncoding=UTF-8
      username: random_matching
      password: random_matching!@34
    slaves:
      - name: slave-1
        url: jdbc:mariadb://localhost:13307/random_matching?serverTimezone=UTC&characterEncoding=UTF-8
      - name: slave-2
        url: jdbc:mariadb://localhost:13308/random_matching?serverTimezone=UTC&characterEncoding=UTF-8
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      #      ddl-auto: update
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        generate-ddl: true
        default_batch_fetch_size: 100

file-path:
  root: /Users/ds/Downloads/springboot/${application.title}/${spring.application.name}

decorator:
  datasource:
    p6spy:
      enable-logging: false