server:
  port: 8002
  shutdown: graceful

application:
  title: matching-king
  
spring:
  application:
    name: matching-api-service
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/random_matching?serverTimezone=UTC
    username: random_matching
    password: random_matching!@34
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      #      ddl-auto: update
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

logging:
  file:
    path: ${file-path.root}/logs
    name: ${spring.config.activate.on-profile}
  config: classpath:logback-${spring.config.activate.on-profile}.xml

---
# LOCAL
spring:
  config:
    activate:
      on-profile: local

file-path:
  root: /Users/ds/Downloads/springboot/${application.title}/${spring.application.name}