server:
  port: 8001
  shutdown: graceful

application:
  title: matching-king

spring:
  application:
    name: auth-api-service
  jackson:
    default-property-inclusion: non_null

logging:
  file:
    path: ${file-path.root}/logs
    name: ${spring.config.activate.on-profile}
  config: classpath:logback-${spring.config.activate.on-profile}.xml

---
# LOCAL
spring:
  config:
    activate:
      on-profile: local

file-path:
  root: /Users/ds/Downloads/springboot/${application.title}/${spring.application.name}

---
# LOCAL
spring:
  config:
    activate:
      on-profile: test

file-path:
  root: /Users/ds/Downloads/springboot/${application.title}/${spring.application.name}