server:
  port: 8001
  shutdown: graceful

spring:
  application:
    name: auth-api-service
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/random_matching?serverTimezone=UTC
    username: random_matching
    password: random_matching!@34
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      #      ddl-auto: update
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

logging:
  level:
    com.soon83: debug
